-- Migration 006: Priority Model
-- Adds ThemeMetrics and entry_signals tables for the Neurologue Priority Model (NPM).
--
-- ThemeMetrics stores time-sliced EVOM scores per theme.
-- entry_signals stores per-entry classification signals generated by the LLM.

CREATE TABLE theme_metrics (
  id                    TEXT PRIMARY KEY,
  theme_id              TEXT NOT NULL REFERENCES themes(id) ON DELETE CASCADE,
  window_start          TEXT NOT NULL,
  window_end            TEXT NOT NULL,
  energy_score          REAL NOT NULL DEFAULT 0.0,
  value_alignment_score REAL NOT NULL DEFAULT 0.0,
  obligation_score      REAL NOT NULL DEFAULT 0.0,
  motivation_score      REAL NOT NULL DEFAULT 0.0,
  priority_score        REAL NOT NULL DEFAULT 0.0,
  open_loops_count      INTEGER NOT NULL DEFAULT 0,
  entries_count         INTEGER NOT NULL DEFAULT 0,
  computed_at           TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(theme_id, window_start, window_end)
);

CREATE INDEX idx_theme_metrics_theme_id  ON theme_metrics(theme_id);
CREATE INDEX idx_theme_metrics_window    ON theme_metrics(window_start, window_end);

CREATE TABLE entry_signals (
  entry_id              TEXT PRIMARY KEY REFERENCES entries(id) ON DELETE CASCADE,
  theme_id              TEXT REFERENCES themes(id) ON DELETE SET NULL,
  length_tokens         INTEGER NOT NULL DEFAULT 0,
  sentiment_score       REAL NOT NULL DEFAULT 0.0,   -- -1 to 1
  emotional_intensity   REAL NOT NULL DEFAULT 0.0,   -- 0 to 1
  obligation_flag       INTEGER NOT NULL DEFAULT 0,  -- boolean (0/1)
  motivation_flag       INTEGER NOT NULL DEFAULT 0,
  value_reference_flag  INTEGER NOT NULL DEFAULT 0,
  open_loop_flag        INTEGER NOT NULL DEFAULT 0,
  computed_at           TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_entry_signals_theme_id ON entry_signals(theme_id);
